### ISSUE TITLE
Issue CmdVersion regularly as a heart-beat to prevent connection from going stale?

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#212] opened 2019-11-30 19:37 UTC
If RPC daemon is connected to the turbo-geth node, and the connection becomes idle, the connection can be silently "squashed" by firewalls after certain time and the next time RPC request comes, the packets would get lost. Eventually, RPC daemon will time out, drop and re-create the connection, but it will take some time. Do you think introducing "regular beats" by issuing `CmdVersion` is a good idea to prevent this?

**Comment by AskAlexSharov** [comment] 2019-12-17 05:55
Done regular ping by CmdVersion from client to server. Not done from Server to client. 
Closing as duplicate of https://github.com/ledgerwatch/turbo-geth/issues/235

**Closed by AskAlexSharov** 2019-12-17 05:55 UTC
