### ISSUE TITLE
Looking ways to collaborate with you

### ISSUE THREAD

**Issue by donequis** [ledgerwatch/turbo-geth#53] opened 2019-07-01 20:18 UTC
Hi there,

I want to collaborate with this project and I'm looking for some starting issues or ways to collaborate. I'm a programmer at Decentraland and we are interested in helping the development of storage rent and other eth 1x improvements.

I read about the state rent proposal and I understand the major points

Last week I could start syncing the node, but it would fail to validate all blocks on restart. Today it doesn't event start to download blocks. Neither in master nor in the eip-2027 branch. Probably there are different ways for testing the node that do not require to syncing it and you may help me pointing those?

Or maybe you know better how I can help you guys

Thanks,

**Comment by AlexeyAkhunov** [comment] 2019-07-01 20:21
Hi Matias, what error message are you getting when you fail to validate blocks on restart?

**Comment by donequis** [comment] 2019-07-02 00:33
Sure. Here's an example. I just passed the `--datadir` flag

```FO [07-01|21:26:50.632] Maximum peer count                       ETH=25 LES=0 total=25
INFO [07-01|21:26:50.632] Starting peer-to-peer node               instance=turbo-geth/v1.9.0-unstable/linux-amd64/go1.12.6
INFO [07-01|21:26:50.642] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}"
INFO [07-01|21:26:50.643] Disk storage enabled for ethash caches   dir=/home/donequis/ethereum2/geth/ethash count=3
INFO [07-01|21:26:50.643] Disk storage enabled for ethash DAGs     dir=/home/donequis/.ethash               count=2
INFO [07-01|21:26:50.643] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [07-01|21:26:50.647] Loaded most recent local header          number=1163270 hash=43e2b0…702b5e td=9659227630046810348 age=3y4mo1d
INFO [07-01|21:26:50.647] Loaded most recent local full block      number=1163270 hash=43e2b0…702b5e td=9659227630046810348 age=3y4mo1d
INFO [07-01|21:26:50.647] Loaded most recent local fast block      number=1163270 hash=43e2b0…702b5e td=9659227630046810348 age=3y4mo1d
INFO [07-01|21:26:50.647] Loaded local transaction journal         transactions=0 dropped=0
INFO [07-01|21:26:50.647] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-01|21:26:50.656] New local node record                    seq=1 id=eb7aaaf0149528f3 ip=127.0.0.1 udp=30303 tcp=30303
INFO [07-01|21:26:50.656] Protocol syncing start 
INFO [07-01|21:26:50.656] Syncing. Is it logging ??? 
INFO [07-01|21:26:50.656] Started P2P networking                   self=enode://af7f9ae9613541e359802a87b7f1c22b8068529bea0bac6942ca828dd2ae30ea85e23741a0c6dc7d8e396aafbbf1ee93d204700a3a116e7dbb9be19d24690ad8@127.0.0.1:30303
INFO [07-01|21:26:50.657] IPC endpoint opened                      url=/home/donequis/ethereum2/geth.ipc
INFO [07-01|21:26:53.481] New local node record                    seq=2 id=eb7aaaf0149528f3 ip=190.245.174.70 udp=30303 tcp=30303
INFO [07-01|21:27:00.656] Block synchronisation started 
WARN [07-01|21:27:05.853] Synchronisation failed, retrying         err="block download canceled (requested)"
INFO [07-01|21:28:03.822] Creating StateDB from latest state       block=1163270
WARN [07-01|21:28:05.079] Synchronisation failed, dropping peer    peer=f5f9fb503b4992ee err="retrieved hash chain is invalid"
WARN [07-01|21:28:21.127] Synchronisation failed, retrying         err="block download canceled (requested)"
ERROR[07-01|21:28:40.727] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000  ConstantinopleFix: 7280000 Engine: ethash}

Number: 1163271
Hash: 0x4ad3157427464d37394bbd581a90d6f74f973690b9738c6335da3319d56259a5
	 0: cumulative: 60883 gas: 60883 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xd460c31052e7493597deb553d796bf864451f2b8c4f622c0ca747a58f8712136 logs: [0xc0000c53f0 0xc0000c5550 0xc0000c5600 0xc0000c56b0] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000040001000000000000000002000000000000000000000000000000000000000000000000000000000400000000000000000100000000000000400000020000080000000000000802000000000000000000000000000000000000000000000000400004000000000000000000000000000000000000000000000000000000000400080000000000000000000000000408000800000000010000000000000000000000000000000000080000000000000000000000000020000000000000120000000000080000000000000000000000000000000000800000 state: 
	 1: cumulative: 81883 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x732ec5c451055b5d6d62dbc58badaaf2ecd28c3a320f463d0e1cc884e16e4437 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 
	 2: cumulative: 102883 gas: 21000 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x667d38b59f41646c7947e154071c2a34988f145b77adc3ea715a0bf705161b5b logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 


Error: Resolving wrong hash for contract , key 000b030a07050c02010803010c040d070107030603060801010d060b0e020b0a0c0a0e04070d0906030c0e0f07010f0a0d090e08030b0f0f0a07090e0f02060210, pos 0, 
expected <8fda2f4562a9703e55ed4a57032e6897da408331fb7872caa7687ee6c5c0d868> , got <a8cf21702d5e71bd2f8fcba8acaf81bb046e425663b6747aaf2eb860e38967d4> 

##############################
 
WARN [07-01|21:28:40.728] Synchronisation failed, dropping peer    peer=f15a73aaf1c1778a err="retrieved hash chain is invalid"
WARN [07-01|21:31:07.339] Synchronisation failed, retrying         err="block body download canceled (requested)"
INFO [07-01|21:31:26.387] Creating StateDB from latest state       block=1163270
WARN [07-01|21:31:26.729] Synchronisation failed, dropping peer    peer=8cfb3f94921b8fe4 err="retrieved hash chain is invalid"
WARN [07-01|21:31:35.704] Synchronisation failed, dropping peer    peer=9a280a3fc90d67f1 err="action from bad peer ignored"
^CINFO [07-01|21:32:00.105] Got interrupt, shutting down... 
INFO [07-01|21:32:00.105] IPC endpoint closed                      url=/home/donequis/ethereum2/geth.ipc
INFO [07-01|21:32:00.105] Blockchain manager stopped 
INFO [07-01|21:32:00.105] Stopping Ethereum protocol 
INFO [07-01|21:32:00.105] Ethereum protocol stopped 
WARN [07-01|21:32:00.105] Synchronisation failed, retrying         err="header processing canceled (requested)"
INFO [07-01|21:32:00.105] Transaction pool stopped 
INFO [07-01|21:32:00.108] Database closed```

**Comment by AlexeyAkhunov** [comment] 2019-07-02 06:48
Thank you for reporting this, there is definitely a bug in resolution that I must have introduced recently, I will be investigating this. There were other reports of this problem

**Comment by AlexeyAkhunov** [comment] 2019-07-02 20:46
The root cause has been identified. The state database gets corrupted in the case when a contract gets deleted by SELF-DESTRUCT and then receives ether in the same block, effectively turning into a non-contract account. When this happens, the storageRoot is not set to the hash of empty tree, as required. This is a regression likely introduced by https://github.com/ledgerwatch/turbo-geth/pull/34 and is only reproducible on pre-Byzantium blocks (that is why it escaped my testing). I will be fixing it shortly

**Comment by AlexeyAkhunov** [comment] 2019-07-03 20:40
Fixed by https://github.com/ledgerwatch/turbo-geth/pull/55

**Closed by AlexeyAkhunov** 2019-07-03 20:40 UTC
