### ISSUE TITLE
Stuck at height 12116676 with "mismatched receipt headers for block 12116677"

### ISSUE THREAD

**Issue by pipermerriam** [ledgerwatch/turbo-geth#1614] opened 2021-03-27 16:58 UTC
#### System information

Geth version: afe551ba1c67d53b17bcc3ff85fe4dcbd9040760
OS & Version: Linux
Commit hash : afe551ba1c67d53b17bcc3ff85fe4dcbd9040760

#### Expected behaviour

Process the block

#### Actual behaviour

Fails to process the block due to an error in the receipt

#### Steps to reproduce the behaviour

:shrug: 

#### Backtrace

````
INFO [03-27|10:57:59.659] [5/14 Execution] Blocks execution        from=12116676 to=12122304
WARN [03-27|10:57:59.694] Synchronisation failed, retrying         err="mismatched receipt headers for block 12116677"
````

**Comment by AlexeyAkhunov** [comment] 2021-03-27 17:41
Thanks for the report. Yes, that is quite weird. Would need to rollback my DB to that point and try to re-run this block. My 2 nodes did go past that block, but they might have been on a different version of the code

**Comment by AlexeyAkhunov** [comment] 2021-03-27 20:14
Drat, I could not reproduce it, just went through that block again... Need to think what diagnostics to request from your DB

**Comment by AlexeyAkhunov** [comment] 2021-03-27 21:02
I am adding a new option to the `cmd/integration` tool, that should allow me to grab your execution traces for that block if you still have them for the next few hours, will post here what you'd need to run to use it. Thanks for your patience

**Comment by AlexeyAkhunov** [comment] 2021-03-27 21:48
@pipermerriam Ok, so the tracing addition is merged to `master`. Please do the following if you can:
1. Pull master branch
2. Build integration tool `make integration`
3. Run the tracing of block 12116677 on your database: `./build/bin/integration stage_exec --chaindata <your_datadir>/tg/chaindata --block 12116677 --txtrace`
4. After that, there should be lots of files in your current directory, one per transaction in that block. Their names look like `txtrace_<txhash>.txt`
5. Could you zip them and get that zip file to me somehow, this would be very helpful. I will look into it with urgency.

Thank you very much in advance!

**Comment by pipermerriam** [comment] 2021-03-29 16:03
sent you a link over discord to a gist with the zip file in it.

**Comment by pipermerriam** [comment] 2021-03-29 16:13
I've been kind of just "running off `master`" for while now.  I'm going to wait a bit before trying to restart from latest master in case you want to do any further debugging on my database.

**Comment by AlexeyAkhunov** [comment] 2021-03-29 18:13
Thanks a lot. This is the transaction that executed differently: https://etherscan.io/tx/0x440de3d9920d04a4bf7f30fe54671c1705677053a939a5dc91b70331e8feae0b

**Comment by AlexeyAkhunov** [comment] 2021-03-29 18:22
Looks like all `SLOAD`s return 0 for some contracts, that's why that tx is doing things differently. If I had to guess, it would some incarnation shenanigans. @pipermerriam Did you keep the full log by any chance? I would like to see your reorgs there

**Comment by AlexeyAkhunov** [comment] 2021-03-29 19:05
And more info - the contract on which `SLOAD` reads zeros is this one: `0xB94F0DFD1B54Af0Fc8dD0997A8ddDE59bAd47dfE`

**Comment by AlexeyAkhunov** [comment] 2021-03-29 19:33
@pipermerriam If you can checkout the branch `various-fixes` (will merge to master soon) and do the following (and show the output), it would be great:

1. `make hack`
2. `/build/bin/hack --action readAccount --account 0xB94F0DFD1B54Af0Fc8dD0997A8ddDE59bAd47dfE --chaindata <your_datadir>/tg/chaindata`

This will print out the storage content of this account and its current incarnation, and perhaps will tell us quickly what is wrong with your DB copy.
Thanks a lot in advance!

**Comment by pipermerriam** [comment] 2021-03-29 19:41
Here's the output.

[issue-1614.log](https://github.com/ledgerwatch/turbo-geth/files/6224104/issue-1614.log)

**Comment by AlexeyAkhunov** [comment] 2021-03-30 04:32
Ok, your DB seems to be corrupted. It does still happen with LMDB, we don't really know why, and we are trying to migrate to MDBX because it does seem to have safer behaviour. Your option is unfortunately to resync :( Thank you for your help!

**Closed** 2021-03-30 05:12 UTC
