### ISSUE TITLE
Assertion 'IS_LEAF(mp)' failed in mdb_cursor_next()

### ISSUE THREAD

**Issue by poma** [ledgerwatch/turbo-geth#1147] opened 2020-09-27 22:19 UTC
#### System information

Geth version: commit `47f59e8fc` (also tested on latest `14288b8cd`, and with docker mounted to the same db, same issue)
OS & Version: OSX 10.5.6

#### Expected behaviour

Sync in successful

#### Actual behaviour

Node fails at sync stage 7

#### Backtrace

````
INFO [09-28|01:09:35.646] Calculating Merkle root                  current key=06030505...
mdb.c:5940: Assertion 'IS_LEAF(mp)' failed in mdb_cursor_next()
SIGABRT: abort
PC=0x7fff71e5433a m=15 sigcode=0
signal arrived during cgo execution
````

Full trace https://gist.github.com/poma/0ca617ab1743f650751658935ce2bd56

**Comment by AskAlexSharov** [comment] 2020-09-28 04:31
Hello. Thank you for report, we will investigate why it happened. 

Here is hack to fix it for you: 
`go run -trimpath ./cmd/integration stage_hash_state --chaindata=/path/to/your/tg/chaindata --reset`
Then just start TG.

**Comment by AlexeyAkhunov** [comment] 2020-09-28 09:09
Another question - how was the node shut down before you restarted it that time?

**Comment by koen84** [comment] 2020-09-29 02:24
I have the same error.  TG catching up sync after i had to reset server (when trying to find me details on an other issue), so in all likelihood no clean shutdown.

**Comment by AlexeyAkhunov** [comment] 2020-09-29 12:32
More context from @poma . The error started happening when he restarted after another error:
```
INFO [09-27|18:59:24.885] Sync stage 10/12. Generate tx lookup index...
INFO [09-27|18:59:31.963] Looking for peers                        peercount=0  tried=4  static=0
INFO [09-27|18:59:41.967] Looking for peers                        peercount=0  tried=4  static=0
INFO [09-27|18:59:51.967] Looking for peers                        peercount=0  tried=4  static=0
INFO [09-27|18:59:54.889] ETL [1/2] Extracting                     from=h                  block=804436   alloc=578.51MiB  sys=6.53GiB numGC=89362
...
INFO [09-27|19:42:43.221] Flushed buffer file                      name=/Users/poma/Library/TurboGeth/etl-temp/tg-sync-sortable-buf319161155 alloc=1.09GiB    sys=6.53GiB numGC=90311
INFO [09-27|19:42:43.242] ETL [1/2] Extracting                     from=h                  block=5698071  alloc=1.09GiB    sys=6.53GiB numGC=90311
INFO [09-27|19:42:54.792] ETL [1/2] Extracting                     from=h                  block=5708204  alloc=797.55MiB  sys=6.53GiB numGC=90318
INFO [09-27|19:43:24.794] ETL [1/2] Extracting                     from=h                  block=5736651  alloc=1.39GiB    sys=6.53GiB numGC=90333
INFO [09-27|19:44:05.441] Flushed buffer file                      name=/Users/poma/Library/TurboGeth/etl-temp/tg-sync-sortable-buf309654982 alloc=1.14GiB    sys=6.53GiB numGC=90342
INFO [09-27|19:44:05.465] ETL [1/2] Extracting                     from=h                  block=5752799  alloc=1.14GiB    sys=6.53GiB numGC=90342
ERROR[09-27|19:44:08.606] Invalid block body RLP                   hash="dd3622…d9fa8a" err="rlp: non-canonical integer (leading zero bytes) for *uint256.Int, decoding into (types.Body).Transactions[72](types.txdata).V"
INFO [09-27|19:44:08.641] etl: temp files removed successfully     total size="8.9 GB"
WARN [09-27|19:44:08.641] Synchronisation failed, retrying         err="tx lookup generation, empty block body 5755737, hash dd3622a9c4cd8bac3b19b7f1f14533bbc15b5f0765518716564f3641a3d9fa8a"
INFO [09-27|19:44:09.863] Sync stage 1/12. Download headers...
```

**Comment by AskAlexSharov** [comment] 2020-10-20 07:38
So, this error happening when using same cursor for Delete and Iterate operations - because LMDB stores some state inside cursor and it allows do only few deletes in the row. MDBX also has this problem and will fixed by https://github.com/erthink/libmdbx/issues/121

Problem solved manually, but to solve it fully - we must use ETL abstraction everywhere (interhashes stage doesn't use it, It will possible after https://github.com/ledgerwatch/turbo-geth/issues/1267 done). 

So, I closing this issue.

**Closed by AskAlexSharov** 2020-10-20 07:38 UTC

**Comment by erthink** [comment] 2020-10-21 00:09
@hyc, I think you should look at this bug.
I fixed this recently in (my nook) `libmdbx`, but all versions of `LMDB` for now could (at least on assertions) crash by a valid sequence of operations.

P.S.
As far as I remember, I fixed several other similar errors, i.e. there are definitely more in LMDB.
Nonetheless I do not always correctly solved your puzzles in the code, so some of my corrections were repeated ;)

**Comment by hyc** [comment] 2020-10-21 20:39
Thanks for the ping, corresponding LMDB patch is in https://git.openldap.org/openldap/openldap/-/merge_requests/194 but still needs a test case.

**Comment by erthink** [comment] 2020-10-23 01:24
@hyc, I used this method of reproduction:
  - according to @AskAlexSharov, I sketched a [simple test](https://gist.github.com/erthink/1e53304762dd2e0146abf31cd09cdfc5) with several deletion options.
  - using a suitable database created on some (I don't know exactly) iteration of the [test script](https://github.com/erthink/libmdbx/blob/master/test/long_stochastic.sh) script.
  - the problem is reproduced when deleting from the `TBL0001` sub-database, about which `mdbx_chk` gives such information:
        Processing 'TBL0001'...
         - key-value kind: usual-key => multi-value, flags: dupsort (0x04)
         - last modification txn#621
         - page size 256, entries 31445
         - b-tree depth 5, pages: branch 3549, leaf 11503, overflow 0
         - summary: 31445 records, 27350 dups, 303226 key's bytes, 1056307 data's bytes, 0 problems

If necessary, I can send a dump of this database.

**Comment by mariuspod** [comment] 2021-02-10 07:50
> Here is hack to fix it for you:
> `go run -trimpath ./cmd/integration stage_hash_state --chaindata=/path/to/your/tg/chaindata --reset`
> Then just start TG.

That worked for me perfectly after having an unclean shutdown of the host due to power outage. Thanks a lot! :+1: 
I had to build version `2021.02.2-alpha` (123710adcd22da970aad810694dd236822ae1f18) to run the command successfully before that I got many mdbx linking errors.

Now my node is synced again! :rocket:

@AskAlexSharov is there some list of useful commands that could restore the node once bad things happen so you don't have to start syncing from scratch ? Last time I had another mdb issue not being able to open the db anymore and I had to start from 0 so I'm really glad this time I could fix the db with your command.

**Comment by AskAlexSharov** [comment] 2021-02-10 09:30
@mariuspod , we have, but self-diagnostic of problem is hard for user.
- `./build/bin/integration stage_*` is the list of commands to manage stages - each command has `--reset` option to reset stage (and all data produced by this stage to 0). 
- We also have several commands to check db integrity and I plan to consolidate them into 1 command: https://github.com/ledgerwatch/turbo-geth/issues/1474
- LMDB: `make db-tools` producing `./build/bin/mdb_*` commands to dump/load/defragment/etc... database - but unlikely it's useful for non-developer.
- MDBX: `make db-tools` producing `./build/bin/mdbx_*` commands to dump/load/defragment/etc... database - and also has mdbx_check for corruption diagnostic.

In general, to discover what we have, you can try to read Readme files in folders: `./cmd/*/Readme.md` 
For example: https://github.com/ledgerwatch/turbo-geth/tree/master/cmd/integration

**Comment by mariuspod** [comment] 2021-02-10 10:21
@AskAlexSharov Thanks for pointing me to the docs!
So basically you could reset at any stage where tg is stuck with an error/exception ?
I'll have to test it a bit with a smaller dataset.

**Comment by AskAlexSharov** [comment] 2021-02-10 10:45
@mariuspod , can't recommend it, because "destroying evidence does not help investigate a crime". But if no other solution - then yes.
